# Generated by Django 5.2.7 on 2025-10-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0005_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(null=True, upload_to="play_image_file_path"),
        ),
    ]
