# Generated by Django 5.2.7 on 2025-11-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0007_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="theatrehall",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
